volumes:
  static_volume:
  postgres_data:

services:
  db:
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  blogicum:
    build: ./blogicum
    env_file: ./.env
    volumes:
      - static_volume:/home/app/blogicum/staticfiles

  gateway:
    build: ./nginx/
    volumes:
      - static_volume:/home/app/blogicum/staticfiles
    ports:
      - 7000:80
