volumes:
  static_volume:
  postgres_data:

services:
  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  blogicum:
    build: ./blogicum
    volumes:
      - static_volume:/home/app/blogicum/staticfiles
    env_file: .env

  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static_volume:/home/app/blogicum/staticfiles
    ports:
      - 7000:80
