volumes:
  static:

services:

  blogicum:
    build: .
    volumes:
      - static:/static/

  gateway:
    build: ./nginx/
    volumes:
      - static/media:/var/www/media/posts_images/
    ports:
      - 7000:80
