version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres
    restart: always
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  blogicum:
    image: belyashnikovatn/blogicum
    volumes:
      - static:/home/app/blogicum/staticfiles
    env_file: ./.env
    depends_on:
      - db

  gateway:
    image: belyashnikovatn/blogicum_gateway
    volumes:
      - static:/home/app/blogicum/staticfiles
    ports:
      - 7000:80
    depends_on:
      - blogicum
