volumes:
  static:

services:
  backend:
    image: belyashnikovatn/blogicum_backend
    env_file: .env
    volumes:
      - static:/backend_static

  gateway:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/nginx-data
    ports:
      - "80:80"