volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data


  blogicum:
    image: belyashnikovatn/blogicum
    env_file: .env
    volumes:
      - static_volume:/home/app/blogicum/staticfiles
      - media_volume:/home/app/blogicum/mediafiles
    depends_on:
      - db

  gateway:
    image: belyashnikovatn/blogicum_gateway
    env_file: .env
    volumes:
      - static_volume:/home/app/blogicum/staticfiles
      - static_volume:/home/app/blogicum/mediafiles
    ports:
      - 7000:80
    depends_on:
      - blogicum
      - db
