volumes:
  static:

services:
  backend:
    image: belyashnikovatn/blogicum_backend
    env_file: .env
    volumes:
      - static:/backend_static

  gateway:
    image: nginx
    env_file: .env
    volumes:
      - static:/nginx-data
    ports:
      - 7000:80