volumes:
  static:

services:
  backend:
    image: belyashnikovatn/blogicum_backend
    env_file: .env
    volumes:
      - static:/backend_static

  gateway:
    image: belyashnikovatn/blogicum_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 7000:80