volumes:
  static_volume:
  postgres_data:

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  blogicum:
    build: ./blogicum
    volumes:
      - static_volume:/home/app/blogicum/staticfiles
    env_file:
      - ./.env.dev

  gateway:
    build: ./nginx/
    volumes:
      - static_volume:/home/app/blogicum/staticfiles
    ports:
      - 7000:80
