version: '3'

volumes:
  static:

services:
  backend:
    image: belyashnikovatn/blogicum_backend
    env_file: .env
    volumes:
      - static:/backend_static

  gateway:
    image: belyashnikovatn/gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/nginx-data
    ports:
      - 8080:80