volumes:
  pg_data:
  static:

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  blogicum:
    image: belyashnikovatn/blogicum
    volumes:
      - static:/home/app/blogicum/staticfiles
    env_file: ./.env
    depends_on:
      - db

  gateway:
    image: belyashnikovatn/blogicum_gateway
    volumes:
      - static:/home/app/blogicum/staticfiles
    ports:
      - 7000:80
    depends_on:
      - blogicum
      - db
